disko_project/disko_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import  include, url
from store import views
from django.views.static import serve

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^store/', include(('store.urls','store'), namespace='store')),
    url(r'^storeadmin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),
]

# include urls of django toolbar, only available in debug mode


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

disko_project/store/urls.py
#import urls from project
from django.conf.urls import url


#import views 
from . import views

urlpatterns = [
    #url(r'^$', views.index), # /store may call method index (view) 
    url(r'^$', views.listing, name='listing'), # /store may call method listing (view)
    url(r'^(?P<id>[0-9]+)/$', views.details, name='details'),
    url(r'^search/$', views.search, name='search'),
]

disko_project/store/models.py
from django.db import models
from django.utils.safestring import mark_safe


# Create your models here.

class Artist(models.Model):
    name = models.CharField('Artist ame',max_length=200, unique=True)

    def __str__(self):
        return self.name

    # change model representation (useful in admin section)
    class Meta:
        verbose_name ='artist'


class Contact(models.Model):
    email = models.EmailField('Email',max_length=100)
    name = models.CharField('Name',max_length=200)

    def __str__(self):
        return self.name

    # change model representation (useful in admin section)
    class Meta:
        verbose_name ='client'

class Album(models.Model):
    reference = models.IntegerField('Album reference',null=True)
    created_at = models.DateTimeField('Creation date',auto_now_add=True)
    available = models.BooleanField('Is album avaible',default=True)
    title = models.CharField('Album title',max_length=200)
    picture = models.FileField('Image album (URL)',upload_to='media/',blank=True,null=True)
    artists = models.ManyToManyField(Artist, related_name='albums', blank=True)

    def __str__(self):
        return self.title
    
    # change model representation (useful in admin section)
    class Meta:
        verbose_name ='album'


class Booking(models.Model):
    created_at = models.DateTimeField('Reservation date',auto_now_add=True)
    contacted = models.BooleanField('Reservation  treated',default=False)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    album = models.OneToOneField(Album, on_delete = models.CASCADE)

    def __str__(self):
        return self.contact.name
    
    # change model representation (useful in admin section)
    class Meta:
        verbose_name ='reservation'

disko_project/store/forms.py
from django import forms
from django.forms.utils import ErrorList
from django.forms import ModelForm, TextInput, EmailInput
from .models import Contact


# here, we want display errors as paragraphs not as a list
class FormatErrorList(ErrorList):

    def __str__(self):
        return self.as_divs()

    def as_divs(self):
        if not self : return ''
        return '<div class="errorlist">%s</div>' % ''.join(['<p class="error">%s</p>' % e for e in self])
    

# generate and validate forms

"""
class ContactForm(forms.Form):
    name = forms.CharField(
        label='Name',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
        )
    
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=True
        )
"""
class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email']
        widget = {
            'name' : forms.TextInput(attrs={'class': 'form-control'}),
            'email' : forms.EmailInput(attrs={'class': 'form-control'})
        }

disko_project/store/views.py
from django.shortcuts import render, get_object_or_404
#from django.http import HttpResponse
from .models import Artist,  Album, Contact, Booking
#from django.template import loader # module loader to load templates
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import ContactForm, FormatErrorList
from django.db import transaction, IntegrityError


# Create your views here.

def index(request):
    # get albums twolve first albums, in order by date creation 
    albums = Album.objects.filter(available=True).order_by('-created_at')[:12]
    #list_albums = ["<li>{}</li>".format(album.title) for album in albums]
    context = {'albums': albums}
    return render(request , 'store/index.html', context)


def listing(request):
    list_albums = Album.objects.filter(available=True)
    paginator = Paginator(list_albums, 9)
    # get page number
    page = request.GET.get('page')
    # send page number to paginator
    try:
        albums = paginator.page(page)
    except PageNotAnInteger:
        # page not an integer, deliver first page
        albums = paginator.page(1)
    except EmptyPage:
        # page out of bounds, deliver last page
        albums = paginator.page(paginator.num_pages)
    # set gabarit context
    context = {'albums': albums, 'paginate': True}
    return render(request, 'store/listing.html', context)



def details(request, id):
    album_id = int(id)
    #album = Album.objects.get(pk=album_id)
    album = get_object_or_404(Album, pk=album_id)
    artists_name = " ".join([artist.name for artist in album.artists.all()])
    # set gabarit context
    if album.picture and hasattr(album.picture, 'url'):
        image = album.picture.url
    else: 
        image = '#'
    context = {
        'album_title': album.title,
        'album_name': artists_name,
        'album_id': album.id,
        'thumbnail':  image
    }
    
    # check request type
    if request.method == "POST":
        # get form infos
        form = ContactForm(request.POST, error_class= FormatErrorList)
        if form.is_valid():
            """ is_valid method also convert the data to python object, 
             to use them, get them from django validation dictionnary """
            email = form.cleaned_data["email"]
            name = form.cleaned_data["name"]

            #email = request.POST.get("email")
            #name = request.POST.get("name")

            # run query try/except to avoid displaying error 500 when error occurred, just display simple error message
            try:
                # specify to treat all queries as transactions
                with transaction.atomic():
                    # get contact of email
                    contact = Contact.objects.filter(email=email)

                    if not contact.exists():
                        # create contact
                        contact = Contact.objects.create(email=email, name=name)
                    else:
                        # get contact from queryset, to make able the user can reserve more than one album
                        contact = Contact.first()
            
                    # get request album
                    album = get_object_or_404(Album, pk=album_id)
                    # create reservation
                    booking = Booking.objects.create(contact=contact, album=album)
                    # set available to false after booking
                    album.available = False
                    album.save()
                    # set context 
                    context = {'album_title': album.title}

                    return render(request, 'store/thanks.html', context)
            except IntegrityError:
                form.errors['internal'] = "Sorry! an error occurred, just trying again."
            
        else:
            context['form_errors'] = form.errors.items()
    else:
        form = ContactForm()
    context['form'] = form
    return render(request, 'store/details.html', context) 

def search(request):
    query = request.GET.get('query')
    if not query:
        albums = Album.objects.all()
        #if not albums.exists():
            #message = "Empty albums"
    else:
        albums = Album.objects.filter(title__icontains=query)

        if not albums.exists():
            # get all albums by matching artists name with query
            albums = Album.objects.filter(artists__name__icontains=query)
       # if not albums.exists():
           #  message = "No albums found"

      #  else:
          #  albums = ["<li>{}</li>".format(album.title) for album in albums]
          #  message = """
           #         Search results:\n
            #        <ul>
             #           {}
              #      </ul>
               # """.format("<li>{}</li>".join(albums))

    title = "Requests results of %s"%query

    context = {
        'albums': albums,
        'title':title
    }
    
    return render(request, 'store/search.html', context)

disko_project/store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Best Seller - Disks</title>
    {% load static %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'store/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link href="{% static 'store/css/business-casual.css' %}" rel="stylesheet" type="text/css">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Best Seller</div>
    <div class="address-bar">Here Found Disks | Best Seller </div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'store:listing' %}">Ours disks</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="blog.html">Blog</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->

        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                {% block content %} {% endblock %}
             </div>
        </div>
    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; K.N.K Website 2020</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'store/js/jquery.js' %}" type="text/javascript"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

disko_project/store/templates/store/details.html
{% extends './base.html' %}

{% block content %}
<hr>
<h1 class="intro-text text-center">{{ album_title }}</h1>
<hr class="detail-separator">
<div class="col-md-6">
  <img src="{{ thumbnail }}" alt="{{ album_title }}" class="img-responsive">
</div>
<div class="col-md-6">
  <div style="margin-bottom:45px">
    <h2 class="text-center artist_name">Artists</h2>
    <p>{{ artists_name }}</p>
  </div>

  <h2 class="text-center artist_name">Reservation: {{ album_title }}</h2>
  <p style="margin-bottom: 20px;">Validate  {{ album_title }} and come take it as soonce as possible! </p>
  <form class="form-inline" action="{% url 'store:details' id=album_id %}" method="post">
    {% csrf_token %} <!-- prevent to cross side requests   forgeries -->
    <div class="form-group {% if form.name.form_errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.name.id_for_label }}" class="control-label">Name</label>
      {{ form.name }}
    </div>
    <div class="form-group {% if form.email.form_errors %}has-warning has-feedback{% endif %}">
      <label for="{{form.email.id_for_label}}" class="control-label">E-mail</label>
      {{ form.email }}
    </div>
    <!-- <input type="hidden" class="hidden" value="{{ album_id }}" name="album_id"> -->

    <button type="submit" class="btn btn-success">Reserve</button>
  </form>

  {% if form_errors %}
    <div class="text-danger">
      {% for key, error in form_errors %}
        <!-- treat html and display error -->
        {% autoescape off %}
          {{ error }}
        {% endautoescape %}
      {% endfor %}
    </div>
  {% endif %}

</div>


{% endblock %}

disko_project/store/templates/store/index.html
{% extends './base.html' %}

 {% block content %} 
    {% include './list.html' with list_title='Ours recent disks' %}
 {% endblock %}

disko_project/store/templates/store/list.html
<!-- list albums -->
<div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">{{ list_title }}
    </h2>
    <hr class="detail-separator">
</div>

{% include './search_from.html' %}

<!-- verify gabarit context results -->
{% if albums|length_is:"0" %}
    <div class="text-center">
      <p>Oops! None results found</p>
    </div>

{% else %}
   
    {% for album in albums %}
        
        <div class="col-md-4 text-center">
            <a href="{% url 'store:details' id=album.id %}" >
                <img Class="img-responsive" src="{{ album.picture.url }}" alt="{{ album.title }}"/>
            </a>
            <h3><a href="{% url 'store:details' id=album.id %}"> {{ album.title }} </a></h3>

            <!--list album artists-->
            {% for artist in album.artists.all %}
                <p> {{ artist.name }} </p>
            {% endfor %}
        </div>
        {% if forloop.counter|divisibleby:3 %} <div class="clearfix"></div> {% endif %}
    {% endfor %}

    {% if paginate %}
        <div class="clearfix"></div>
        <nav aria-label="...">
            <ul class="pager">
                {% if albums.has_previous %}
                    <li> <a href="?page={{ albums.previous_page_number }}"> Previous </a></li>
                {% endif %}
                {% if albums.has_next %}
                    <li> <a href="?page={{ albums.next_page_number }}"> Next </a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}


{% endif %}

disko_project/store/templates/store/listing.html
{% extends './base.html' %}

 <!-- send list_title to gabarit -->

 {% block content %} 
    {% include './list.html' with list_title='All disks' %}
 {% endblock %}

disko_project/store/templates/store/search.html
{% extends './base.html' %}

{% block content %}

    {% include './list.html' with list_title=title %}

{% endblock %}

disko_project/store/templates/store/search_from.html
<div class="col-lg-12 detail-separator">
    <form class="col-md-6 col-md-offset-3 text-center" action="{% url 'store:search'%}" method="get" accept-charset="utf-8">
        <div class="form-group">
            <label for="searchForm"> Search disk </label>
            <input id="searchForm" class="form-control" name="query">
        </div>
        <span class="help-block" id="helpBlock"> Search your favorite disk just by enter title or name of your artist </span>
    </form>
</div>

disko_project/store/templates/store/thanks.html
{% extends './base.html' %}
{% block content %}
    <hr>
    <h1 class="intro-text text-center"> Thank you for always trusting us </h1>
    <hr class="detail-separator">
    <p> the album {{album_title}} was booking successfully! </p>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe src="https://www.youtube.com/embed/ZSbuiKMdgqA" frameborder="0" allowfullscreen></iframe>
    </div>
{% endblock %}